export const REQUEST_PRODUCTS = "REQUEST_PRODUCTS";
export const REQUEST_PRODUCTS_SUCCESS = "REQUEST_PRODUCTS_SUCCESS";
export const REQUEST_PRODUCTS_FAIL = "REQUEST_PRODUCTS_FAIL";

export const REQUEST_PRODUCT = "REQUEST_PRODUCT";
export const REQUEST_PRODUCT_SUCCESS = "REQUEST_PRODUCT_SUCCESS";
export const REQUEST_PRODUCT_FAIL = "REQUEST_PRODUCT_FAIL";
